# Generated by Django 4.2.7 on 2024-01-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvrr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default=' ', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fname',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lname',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
    ]
