# Generated by Django 4.2.7 on 2024-01-25 12:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mvrr', '0004_userprofile_is_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenseno', models.CharField(max_length=15)),
                ('idno', models.CharField(max_length=15)),
                ('license_pic', models.ImageField(blank=True, null=True, upload_to='kyc_uploads/')),
                ('id_pic', models.ImageField(blank=True, null=True, upload_to='kyc_uploads/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mvrr.userprofile')),
            ],
        ),
    ]
