# Generated by Django 4.2.7 on 2024-01-25 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mvrr', '0005_kyc'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('licenseno', models.CharField(max_length=20)),
                ('idno', models.CharField(max_length=20)),
                ('licensepic', models.ImageField(upload_to='kyc_uploads/')),
                ('idpic', models.ImageField(upload_to='kyc_uploads/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='KYC',
        ),
    ]
