# Generated by Django 4.2.7 on 2024-01-29 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvrr', '0007_bikedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikedata',
            old_name='chessis_no',
            new_name='chassis_no',
        ),
    ]
