# Generated by Django 4.2.7 on 2024-01-29 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvrr', '0007_bike_bikeimage'),
        ('mvrr', '0008_rename_chessis_no_bikedata_chassis_no'),
    ]

    operations = [
    ]
