# Generated by Django 4.2.7 on 2024-01-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvrr', '0008_rename_chessis_no_bikedata_chassis_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikedata',
            name='biketype',
            field=models.CharField(choices=[('CLASSIC', 'Classic'), ('STREET BIKE', 'Street Bike'), ('COMMUTER', 'Commuter'), ('SPORTS BIKE', 'Sports Bike'), ('CHAPRI BIKE', 'Chapri Bike')], default='CLASSIC', max_length=20),
        ),
    ]
