# Generated by Django 4.2.7 on 2024-01-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvrr', '0010_remove_bikeimage_bike_delete_bike_delete_bikeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikedata',
            name='biketype',
            field=models.CharField(choices=[('CLASSIC', 'Classic'), ('STREET BIKE', 'Street Bike'), ('COMMUTER', 'Commuter'), ('SPORTS BIKE', 'Sports Bike'), ('CHAPRI BIKE', 'Chapri Bike')], default='CLASSIC', max_length=20),
        ),
    ]
