# Generated by Django 4.2.7 on 2024-02-01 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvrr', '0012_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
