# Generated by Django 4.2.7 on 2024-01-31 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvrr', '0013_remove_bikedata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikedata',
            name='bookedat',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 16, 8, 58, 720948)),
        ),
    ]
