# Generated by Django 4.2.7 on 2024-02-01 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvrr', '0015_alter_bikedata_bookedat_bookingdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdata',
            name='bikename',
        ),
        migrations.RemoveField(
            model_name='bookingdata',
            name='bikepic',
        ),
        migrations.RemoveField(
            model_name='bookingdata',
            name='biketype',
        ),
        migrations.RemoveField(
            model_name='bookingdata',
            name='chassis_no',
        ),
        migrations.RemoveField(
            model_name='bookingdata',
            name='color',
        ),
        migrations.RemoveField(
            model_name='bookingdata',
            name='company',
        ),
        migrations.RemoveField(
            model_name='bookingdata',
            name='dop',
        ),
        migrations.RemoveField(
            model_name='bookingdata',
            name='onrname',
        ),
        migrations.RemoveField(
            model_name='bookingdata',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bookingdata',
            name='regno',
        ),
        migrations.AlterField(
            model_name='bikedata',
            name='bookedat',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 16, 23, 0, 666168)),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='bookedat',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 16, 23, 0, 666168)),
        ),
    ]
