# Generated by Django 4.2.7 on 2024-02-02 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvrr', '0016_remove_bookingdata_bikename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdata',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bikedata',
            name='bookedat',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 12, 16, 34, 906086)),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='bookedat',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 12, 16, 34, 906086)),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
