# Generated by Django 4.2.7 on 2024-02-03 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvrr', '0013_delete_booking'),
        ('mvrr', '0017_bookingdata_duration_alter_bikedata_bookedat_and_more'),
    ]

    operations = [
    ]
