# Generated by Django 4.2.7 on 2024-02-05 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvrr', '0021_userprofile_balance_alter_bikedata_bookedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikedata',
            name='bookedat',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 23, 43, 21, 713088)),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='bookedat',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 23, 43, 21, 713088)),
        ),
    ]
