# Generated by Django 4.2.7 on 2024-02-08 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvrr', '0024_alter_bikedata_bookedat_alter_bookingdata_bookedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikedata',
            name='bookedat',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 12, 33, 9, 595867)),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='bookedat',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 12, 33, 9, 596867)),
        ),
        migrations.DeleteModel(
            name='OwnerData',
        ),
    ]
